#!/usr/bin/env bash

# mt midi
# lists subcommands
# lists devices

# inputs are indexed by character
# outputs are indexed by numbers

# TODO: Implement this in node

if [[ -z "$1" ]]; then
	$(dirname $0)/lib/get-midi-ports
fi

