#!/usr/bin/env node

// keeps a list of jobs
// exits when list is empty

// when called, checks if a server daemon is already running
// and if so adds the job to it
// otherwise, start a new daemon and send the job to it

var fs = require('fs');

var {Jobs} = require('./lib/store');
var jobs = new Jobs();

var {talk, cry} = require('./lib/utils');

var files = {
	pid: '.pid',
	stdout: 'info.log',
	stderr: 'error.log',
}

function isPidRunning(pid) {
	try {
		return process.kill(pid, 0);
	}
	catch(err) {
		return false;
	}
}

function checkIfRunning() {
	return new Promise((done, fail) => {
		fs.readFile(files.pid, 'utf8', (err, data) => {
			if(err) {
				return done({isRunning: false});
			}
			var pid = parseInt(data.trim(), 10);
			if(isNaN(pid)) {
				return fail(new Error('pid invalid'));
			}
			if(isPidRunning(pid)) {
				return done({isRunning: true, pid: pid});
			}
			return done({isRunning: false});
		});
	});
}

function startServer() {
	return new Promise((done, fail) => {
		var daemon = require('daemon').daemon(module.filename, ['daemon'], {
			stdout: fs.openSync(files.stdout, 'a'),
			stderr: fs.openSync(files.stderr, 'a'),
		});
		// HACK: Hopefully we've started at this point
		setTimeout(() => {
			talk('STARTED', new Date());
			done({isRunning: true});
		}, 500);
	});
}

function ensureServer() {
	return checkIfRunning()
	.then((info) => {
		if(!info.isRunning) {
			return startServer();
		}
		return info;
	})
	.catch(cry);
}

function setupPid() {
	var startTime = (new Date()).getTime();
	return new Promise((done, fail) => {
		process.on('exit', () => {
			fs.unlinkSync(files.pid);
			var ranFor = (new Date()).getTime() - startTime;
			talk('STOPPED', new Date());
			talk(`Ran for ${(ranFor / 1000).toFixed(2)} seconds`);
		});
		fs.writeFile(files.pid, process.pid, (err) => {
			if(err) {
				fail(err);
			}
			done();
		});
	})
}

function launchScheduler() {
	require('./lib/scheduler').create();
}

function addJob(job) {
	ensureServer()
	.then(() => jobs.add(job))
	.then(() => jobs.close())
	.catch(cry);
}

function run() {
	return Promise.all([
		setupPid(),
		launchScheduler()
	]);
}


function main(argv) {
	talk(`in mt-server main ${argv}`);
	// If there's already a pid file, don't start
	checkIfRunning()
	.then(({isRunning}) => {
		if(isRunning) {
			cry('ALREADY RUNNING');
			process.exit(1);
		}
		if(argv[2] === 'daemon') {
			return run();
		}
		else {
			return ensureServer();
		}
	})
	.catch(cry);
}

if(require.main === module) {
	main(process.argv);
	// process.exit(0);
}

module.exports = {
	addJob
};