#!/usr/bin/env node

// TODO: Expose this as a more usable library like jobs, files and tags

var midi = require('midi');

var {talk} = require('./utils');

function outPortNoToId(number) {
	return number;
}
function inPortNoToId(number) {
	return String.fromCharCode(number + 65);
}


function getInPorts() {
	var input = new midi.input();

	var portCount = input.getPortCount();
	var ret = [];
	for(var i = 0; i < portCount; i++) {
		ret.push([inPortNoToId(i), input.getPortName(i)]);
	}
	return ret;
}

function getOutPorts() {
	var output = new midi.output();

	var portCount = output.getPortCount();
	var ret = [];
	for(var i = 0; i < portCount; i++) {
		ret.push([outPortNoToId(i), output.getPortName(i)]);
	}
	return ret;
}

function printPorts(title, ports) {
	if(ports.length) {
		talk(`${title}:`);
		for([id, name] of ports) {
			talk(`${id}: ${name}`);
		}
	}
	else {
		talk(`No ${title}!`);
	}
}

printPorts("MIDI Inputs", getInPorts());
talk();
printPorts("MIDI Outputs", getOutPorts());

process.exit(0);